### ISSUE TITLE
Use AwsCredentials from AWSSDK

### ISSUE THREAD

**Issue by damianh** [AllocZero/EfficientDynamoDb#104]
This library defines it's own `AwsCredentials` type which doesn't have the support for various things that the standard `AwsCredentials` from the AWSSDK supports (i.e. credential files, profiles, ec2 instance roles, environment variables etc). Can the SDK version be used instead? If not, I expect this library to not be useable in a significant number of situations which would be unfortunate because it looks great.

**Comment by lezzi** [comment]
Thanks for pointing out the importance of this feature and creating the issue. Recently we received similar feedback and I think this is going to be one of the most priority features alongside testability improvements.

So far we didn't plan to reference SDK libraries. One of the considerations is to ship another package that depends on SDK Core project to reuse the functionality we don't want to reimplement.

**Comment by lezzi** [comment]
Brainstorming.

I think we definitely miss an async abstraction layer over credentials, some SDK credentials can change/refresh over time and atm it is only possible to achieve by recreating the context, which is not acceptable.

What I don't like in the SDK Core credentials implementation:
1. Async implementations use `Task.Run` for IO-related work. Not all implementations are really async, most likely it is the reason why `Task.Run` is used.
2. Aggressive semaphore locking. From what I understand every single request goes through semaphore lock, this is a big overkill for small requests.

What I don't like in SDK Core project overall - it contains too many things we don't need and as I mentioned above, the things we need can cause performance degradation.

We can create a temporary separate package that adapts SDK `AwsCredentials` class into EfficientDynamoDb abstraction, but the question here is it even worth time spent comparing to implementing each credential approach from scratch.

My main concern about implementing credentials from scratch - they are pretty unique, can be time-consuming/hard to test.

**Comment by damianh** [comment]
I pretty much use all the credential mechanisms in some form in various places. Having a separate / alternative approach _just_ for this library + DynamoDB will meet resistance from the teams I work with. The security side of the house will also raise questions - AWSSDK is official, supported and battle tested, your alternative (unfortunately) will probably not meet this criteria (initially anyway).

I understand that you don't want a direct reference, so an extension package would work. 

Requiring implementing credentials from scratch would be a serious undertaking. It's concerning that you feel you need to go such a direction. I'm wondering if the aws folks are aware of the issues with it? (tagging @normj )

**Comment by lezzi** [comment]
Yeah, I didn't pay much attention to the security side of the question, people tend to be extremely cautious when it comes to credentials and 3rd party libraries. It is another argument in favor of reusing the Core credentials.

**Comment by lezzi** [comment]
Couple more thoughts about this topic.

First, a random idea out of my head. In order to slightly improve the performance, we could ask for a `TimeSpan` TTL value when SDK `AwsCredentials` object is wrapped into the EfficientDynamoDb abstraction. This TTL value will inform the library about how long it can reuse the `ImmutableCredentials` object. For example `TimeSpan.Zero` would mean that every single request will trigger `AWSCredentials.GetCredentialsAsync` like SDK does and `TimeSpan.FromSeconds(60)` would mean that credentials call is made not more often than every 60 seconds. We can also consider reusing the `PreemptExpiryTime` property to make sure that TTL is safe to apply.

Second, it looks really weird why `ImmutableCredentials.Copy` is called every single time. It is immutable, it is even called immutable.

**Comment by firenero** [comment]
@damianh We added support for AWS SDK credentials. Check [this section](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/sdk-compatibility#credentials) to see how to use it. Feel free to ask any questions here as well.

Min `EfficientDynamoDb` package version required: `0.9.2-alpha.0.11`
Min `EfficientDynamoDb.Credentials.AWSSDK` package version required: `0.9.1`

**Comment by lezzi** [comment]
Closing the issue since the stable 0.9.2 version is out already.
