### ISSUE TITLE
Signature failure with saml tokens

### ISSUE THREAD

**Issue by CatalinAdlerDF** [AllocZero/EfficientDynamoDb#107]
Hi,

In our org we use session tokens and I personally use the saml2aws tool to generate short lived tokens.
I've been able to use the official aws sdk to call ddb, using the document apis, but I cannot get the efficient low-level apis to work.

I'm getting a signature validation failure from the ddb apis.

What is do is use the sdk CredentialProfileStoreChain to get the aws sdk creds to construct an efficient aws creds class with key, secret and token, and then use the low-level api to get 1 item. 

Getting `The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method`

**Comment by lezzi** [comment]
Thank you for raising the issue. It looks like the signer has a bug related to tokens. I am going to check it out within the next couple of hours.

**Comment by lezzi** [comment]
@CatalinAdlerDF it should be fixed in the [0.9.1-alpha.0.13](https://www.nuget.org/packages/EfficientDynamoDb/0.9.1-alpha.0.13)

Let me know if you are still facing any problems. I will leave this issue open until your confirmation.

**Comment by CatalinAdlerDF** [comment]
I can confirm the problem is solved with 0.9.1-alpha.0.13
