### ISSUE TITLE
Couldn't parse DateTime ddb value from '2021-10-22T09:10:00+10:00'

### ISSUE THREAD

**Issue by josephj-acmo** [AllocZero/EfficientDynamoDb#166]
Please see the error I am getting when retrieving a date time value.
![image](https://user-images.githubusercontent.com/37004334/143197086-7f11dac6-9c95-4904-a2f3-9611dc93e1bc.jpeg)

Not sure if this is an issue in the SdkDateTimeDdbConverter converter, or issue with the date value we have got in the database. Could you please assist? Thanks.

**Comment by lezzi** [comment]
Hey. Please check the `DateTime` documentation [here](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/sdk-compatibility#datetimes), your format is different from both AWS SDK and default library format.

If you can't or don't want to change the `DateTime` format in the db, then you will need to apply a custom converter.
For `DateTime` we already have a base converter class called `DateTimeDdbConverter`, you can inherit from it and pass your custom format in the constructor, like this:

```
public class CustomDateTimeConverter : DateTimeDdbConverter
{
    public CustomDateTimeConverter() : base("yyyy-MM-ddTHH:mm:ssK")
    {
    }
}
```

And then apply the converter either per property or per dynamodb context, check the [docs here ](https://alloczero.github.io/EfficientDynamoDb/docs/dev_guide/dev-guide/high-level/converters).

Keep in mind that the format I used in the example is just an example, it may work in your case, but I don't know how the dates were saved in the db, so you may need to adjust it.

**Comment by josephj-acmo** [comment]
You were absolutely right, the date entered in the database was not in any standard format. Thanks again for your help.
