### ISSUE TITLE
Query using GSI

### ISSUE THREAD

**Issue by josephj-acmo** [AllocZero/EfficientDynamoDb#168]
Could you please advise if it is possible to query using a GSI with this library? I tried the below:

`var condition = Condition<StoreProduct>.On(x => x.URL).EqualTo(Url);
var items = await _context.Query<StoreProduct>()
    .FromIndex(@"GSIStoreProductsByURL")
    .WithKeyExpression(condition)
    .ToListAsync();`
However got the error "ValidationException: One or more parameter values were invalid: Condition parameter type does not match schema type"

Any inputs or sample code will be highly appreciated. Thanks.

**Comment by firenero** [comment]
Hey @josephj-acmo. Yes, it's possible and your index code is correct. However, there is an issue with your condition. Could you please tell me C# types of `x.URL` and `Url`.  And what is the underlying DynamoDB type?

**Comment by josephj-acmo** [comment]
Thanks for confirming, I think I figured out the issue. Thanks for your help.

**Comment by eladyko** [comment]
It should be prohibited to close issues with "I think I figured out the issue" without describing it
