### ISSUE TITLE
Pagination Query

### ISSUE THREAD

**Issue by kkumarkarthik** [AllocZero/EfficientDynamoDb#169]
Hello, 

We would like to know if there is a way to retrieve a specific number of items, using the query ToPageAsync() method.

For instance, there are 100 items in the database, we would like to retrieve only the first 10 items on the first request, with the pagination token.
During the second request with the pagination token, we like to retrieve the next 10 items.

Could you please let us know if it is feasible?

Thanks
KK

**Comment by firenero** [comment]
Yes, you can do this by using `WithLimit(10)` method when configuring the query. 
Your case would look somewhat like this:

```csharp
var page = context.Query<SomeEntity>()
                  .WithKeyExpression(keyExpression)
                  .WithLimit(10)
                  .ToPageAsync();
```

Then you can use `page.PaginationToken` to get the next elements like this:

```csharp
var nextPage = context.Query<SomeEntity>()
                      .WithKeyExpression(keyExpression)
                      .WithLimit(10)
                      .WithPaginationToken(page.PaginationToken)
                      .ToPageAsync();
```

If you want to do the same for all items but only want to load them in batches of 10 (or any other batch size), I'd recommend you using the `ToAsyncEnumerable()` method:

```csharp
var query = context.Query<SomeEntity>()
                   .WithKeyExpression(keyExpression)
                   .WithLimit(10);

await foreach (var item in query.ToAsyncEnumerable())
{
  // Do something
}
```

More details about this approach are in the [Pagination section](https://alloczero.github.io/EfficientDynamoDb/docs/dev_guide/dev-guide/high-level/read#pagination) in docs.

**Comment by kkumarkarthik** [comment]
Thanks a lot, @firenero .
