### ISSUE TITLE
ValidationException: Value provided in ExpressionAttributeNames unused in expressions: keys: {#f2}

### ISSUE THREAD

**Issue by kkumarkarthik** [AllocZero/EfficientDynamoDb#170]
Hello,

We are trying to use Condition and Projected Attributes together and the following error is thrown and we attached the stack trace.
**ValidationException: Value provided in ExpressionAttributeNames unused in expressions: keys: {#f2}**
[stacktrace.txt](https://github.com/AllocZero/EfficientDynamoDb/files/7725024/stacktrace.txt)

Following is our code

var filter = Condition.ForEntity<User>();
var condition = Joiner.And(filter.On(t => t.PK).EqualTo(string.Concat("USER#", UserId)), filter.On(t => t.SK).BeginsWith("USERTAG#"));
var items = _dbcontext.Query<Entities.User>()
                           .WithProjectedAttributes(j=>j.PK,j=>j.SK)
                           .WithKeyExpression(condition)
                           .ToListAsync().Result;

If we have only one param as below, it works.

var items = _dbcontext.Query<Entities.User>()
                           **.WithProjectedAttributes(j=>j.SK)**
                           .WithKeyExpression(condition)
                           .ToListAsync().Result;

Could you please help us to identify the problem?

Thanks
KK

**Comment by lezzi** [comment]
Hey @kkumarkarthik, it was fixed and is available in the `0.9.13-alpha.0.5`, can you try it out?

**Comment by kkumarkarthik** [comment]
Hi @lezzi,

Thanks, It works now.
