### ISSUE TITLE
connect to 'amazon/dynamodb-local'

### ISSUE THREAD

**Issue by Newp** [AllocZero/EfficientDynamoDb#172]
I use 'amazon/dynamodb-local' for unit test operation.
In aws-sdk, ServiceURL (Amazon.Runtime) of Amazon.DynamoDBv2.AmazonDBCconfig.It can be used through Amazon.DynamoDBv2.AmazonDynamoDBClient to which ClientConfig) is applied.

DynamoDBCContext can be accessed based on Context by receiving the Amazon DynamoDBCclient created above from the creator. I would like you to let me know if you are supporting or planning to support this function.

Thank you.

**Comment by Newp** [comment]
https://github.com/AllocZero/EfficientDynamoDb/pull/174/files#r777128086

There is a way to approach it like the link above, but I confirmed that it is approached by Dynamo DbContext, but it looks good if there is something related to readme.

**Comment by lezzi** [comment]
Hey @Newp. I see you have already figured it out. I can confirm that `RegionEndpoint.Create` is the correct way to connect to the local instance. We will improve the docs on the website. A small example just in case:

```
var endpoint = RegionEndpoint.Create(RegionEndpoint.EUWest1, "http://localhost:8000");
var credentials = new AwsCredentials("test", "test");
var localContext = new DynamoDbContext(new DynamoDbContextConfig(endpoint, credentials));
```
