### ISSUE TITLE
DynamoDbVersionAttribute is not working

### ISSUE THREAD

**Issue by Newp** [AllocZero/EfficientDynamoDb#181]
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBContext.VersionSupport.html

[DynamoDbTable("Sample")]
public class SimpleEntity
{

    [DynamoDbProperty("PK", DynamoDbAttributeType.PartitionKey)]
    public string PK { get; set; }

    [DynamoDbProperty("SK", DynamoDbAttributeType.SortKey)]
    public string SK { get; set; }

    [DynamoDbProperty(nameof(Text))]
    public string Text { get; set; }

    [DynamoDbVersion]
    public int? Version { get; set; }  // This value is not stored in db and is not verified.
}

**Comment by firenero** [comment]
Hi @Newp, you're missing the `DynamoDbProperty` attribute on your [version property](https://alloczero.github.io/EfficientDynamoDb/docs/dev_guide/dev-guide/high-level/attributes/#dynamodbversion).
