### ISSUE TITLE
Clarification on thread-safe and DI type, transient, scoped or singleton

### ISSUE THREAD

**Issue by wjax** [AllocZero/EfficientDynamoDb#189]
This is just to ask for a clarification regarding thread safety of the library.
I have not found any place where it talks about this.

Can DynamoDbContext be injected as a singleton?

Many thanks

**Comment by firenero** [comment]
Yes, `DynamoDbContext` is thread-safe so you can use it as a singleton

**Comment by wjax** [comment]
Many thanks
