### ISSUE TITLE
Global and Local secondary indexes

### ISSUE THREAD

**Issue by funkel1989** [AllocZero/EfficientDynamoDb#201]
Hello,

I looked through your documentation and did not find anything on querying global or local secondary indexes. Do you have an example of this by any chance or can you point me to the docs that show how to do it?

**Comment by firenero** [comment]
Hi @funkel1989 

You need to use the fluent API method `.FromIndex("IndexName")` and use the primary key of that GSI configured in DDB. It's not the first question about indexes but I haven't got a chance to update our docs yet. Hopefully, I will do it soon. Meantime you can use an example from the old ticket #168

**Comment by funkel1989** [comment]
This worked. Thank you!
