### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Aux** [AllocZero/EfficientDynamoDb#206]
I figured you wouldn't want a whole PR just for this one little character. There's a small typo in the documentation at this line.

https://github.com/AllocZero/EfficientDynamoDb/blob/master/website/docs/dev_guide/high_level/attributes.md?plain=1#L31

I'm guessing `FirstName` is supposed to be `first_name` and not `fist_name`.

**Comment by firenero** [comment]
Hi @Aux,

Thanks for pointing this out. Feel free to submit a PR if you want. It would take some time for me to get to it so I'm happy to merge your PR.

**Comment by Neha-Balaji** [comment]
Hi, My firm is holding an internal workshop to make us aware of our process for contributing to open source projects. So I would like to take this small change to get familiarized with the process. I will work on this shortly. Thanks.

**Comment by firenero** [comment]
I've fixed the typo. It's not yet applied to the website because of expired deploy keys. I will sort it out later.

**Comment by firenero** [comment]
Keys were updated and the change is now live. 

Thanks for reporting this @Aux
