### ISSUE TITLE
Using transact write buildeer

### ISSUE THREAD

**Issue by TheBreadGuy** [AllocZero/EfficientDynamoDb#221]
(EDIT:came to me just after posting,  i'm noob leaving this here incase use to anyone.  )

POST

is this correct way to use builder? i am getting null error on condition . is it write items not getting  added\? or my qurey? i'm not sure how to debug it.

            var defaultQuantity = 0;
            var transactWriteBuilder = _dynamoDbContext.TransactWrite()
                 .WithClientRequestToken(Guid.NewGuid().ToString());

            foreach (var item in itemsToRemove)
            {

                transactWriteBuilder.WithItems(
                    Transact.UpdateItem<InventoryItem>().
                    WithPrimaryKey(item.PartitionKey, item.SortKey).
                    On(x => x.Quantity).Decrement(defaultQuantity, item.Quantity).
                    WithCondition(Condition<InventoryItem>.On(x => x.Quantity).GreaterThanOrEqualTo(item.Quantity)));
            }
            await transactWriteBuilder.ExecuteAsync();

**Comment by TheBreadGuy** [comment]
transactWriteBuilder = transactWriteBuilder.WithItems(

correct line needed

**Comment by firenero** [comment]
Hi @TheBreadGuy 

Your latest code is correct. In my projects I usually use LINQ for such cases:
```csharp
var updateItems = itemsToRemove.Select(item => 
    Transact.UpdateItem<InventoryItem>()
        .WithPrimaryKey(item.PartitionKey, item.SortKey)
        .On(x => x.Quantity).Decrement(defaultQuantity, item.Quantity)
        .WithCondition(Condition<InventoryItem>.On(x => x.Quantity).GreaterThanOrEqualTo(item.Quantity))
);

transactWriteBuilder = transactWriteBuilder.WithItems(updateItems);
```

**Comment by TheBreadGuy** [comment]
ok thanks i'll try that also.

**Comment by firenero** [comment]
Closing this one as resolved.
