### ISSUE TITLE
No way to set ReturnConsumedCapacity for BatchGet and BatchWrite requests using builders

### ISSUE THREAD

**Issue by diopolgg** [AllocZero/EfficientDynamoDb#222]
The builders for `BatchGet` and `BatchWrite` operations for some reason don't support requesting `ReturnConsumedCapacity` and get the `ConsumedCapacity` in the response (no `ToResponseAsync` for the builders). Although it is supported by the AWS API and also included in low level API models.

We wanted to instrument the consumed capacity for some requests we made using builders, and this would be awesome to have.

All other operations cover this, except these.

**Comment by firenero** [comment]
Hi @diopolgg. Thanks for reporting it. 

Since it's a minor issue that can be mitigated using the low-level API I can't commit to a timeline for adding a high-level API. However, we're open to contributions and happy to review PRs to get this API implemented faster.

**Comment by firenero** [comment]
It's now available in [v0.9.16](https://www.nuget.org/packages/EfficientDynamoDb/0.9.16)
