### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by bill-poole** [AllocZero/EfficientDynamoDb#233]
The [writing data](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/high-level/write) page in the documentation has an example invoking `ToEntityAsync()` [here](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/high-level/write#putitem) and [here](https://alloczero.github.io/EfficientDynamoDb/docs/dev-guide/high-level/write#updateitem), whereas I suspect it should actually be `ToItemAsync()`, given that there is no such method `ToEntityAsync()`.

**Comment by firenero** [comment]
You're right @bill-poole, thanks for reporting it. I fixed it in #234 alongside another bug in docs I'd noticed.
