### ISSUE TITLE
"Invalid attribute value type" exception with Boolean property

### ISSUE THREAD

**Issue by SailAwayWine** [AllocZero/EfficientDynamoDb#252]
When applying DynamoDBProperty to a Boolean, PutItemAsync throws ValidationException "Invalid attribute value type"

Changing the type to Integer resolves the issue.

**Comment by firenero** [comment]
@SailAwayWine can you please provide code of your entity that leads to this error? I can't reproduce the issue on my side. The only scenario I can think of that can lead to this issue is mapping primary key that has type `Number` in DDB to bool property in C#.

**Comment by SailAwayWine** [comment]
Yes.  Looks like using a BOOL as the Hash Key for a Global Secondary Index is not supported by DynamoDB, which is what I was trying to do.  Sorry for the false bug.
