### ISSUE TITLE
Can't execute empty batch write item request

### ISSUE THREAD

**Issue by devtekve** [AllocZero/EfficientDynamoDb#255]
I was testing a batchwrite operation deleting and I found an unexpected behavior. 

If you write the batch like the following
```csharp
protected async Task<IEnumerable<TEntity>> DeleteAsync(IEnumerable<TEntity> items, CancellationToken cancellationToken = default)
{
    items = items.ToList();
    var batchWrite = context.BatchWrite();
    batchWrite.WithItems(
        items.Select(item => Batch.DeleteItem<TEntity>().WithPrimaryKey(item.RecordId, item.Version))
    );
    await batchWrite.ExecuteAsync(cancellationToken);
    return items;
}
```

It will fail because `WithItems` doesn't persist the items on the `batchWrite` instance. It fails with `Can't execute empty batch write item request.`

### Workaround
In order to make it work, you need to do call `executeAsync()` immediately after the `withItems()` call, like in the following example: 

```csharp
protected async Task<IEnumerable<TEntity>> DeleteAsync(IEnumerable<TEntity> items, CancellationToken cancellationToken = default)
{
    items = items.ToList();
    await context.BatchWrite().WithItems(
        items.Select(item => Batch.DeleteItem<TEntity>().WithPrimaryKey(item.RecordId, item.Version))
    ).ExecuteAsync(cancellationToken);
    return items;
}
```

#### Side note
Since my goal with the first approach was to have things a little bit separate from the "preparing items" to the actual deletion, another little workaround to keep things "separate" is:

```csharp
protected async Task<IEnumerable<TEntity>> DeleteAsync(IEnumerable<TEntity> items, CancellationToken cancellationToken = default)
{
    items = items.ToList();
    var deleteRequests = items.Select(item => Batch.DeleteItem<TEntity>().WithPrimaryKey(item.RecordId, item.Version));
    await context.BatchWrite().WithItems(deleteRequests).ExecuteAsync(cancellationToken);
    return items;
}
```

Hopefully if somebody else encounters this issue they now know a quick workaround.

**Comment by firenero** [comment]
`WithItems` is a builder method that returns new instance instead of modifying existing one (similarly to how `string` works in C#). In fact, all builder methods in EfficientDynamoDb behave this way. So if you rewrite your first approach like that, it will work as expected:

```csharp
protected async Task<IEnumerable<TEntity>> DeleteAsync(IEnumerable<TEntity> items, CancellationToken cancellationToken = default)
{
    items = items.ToList();
    var batchWrite = context.BatchWrite();
    batchWrite = batchWrite.WithItems(
        items.Select(item => Batch.DeleteItem<TEntity>().WithPrimaryKey(item.RecordId, item.Version))
    );
    await batchWrite.ExecuteAsync(cancellationToken);
    return items;
}
```
